[theme]
base="light"
secondaryBackgroundColor="#f7f7f7"

[client]   
#toolbarMode="minimal"

[server]
disconnectedSessionTTL = 600
enableXsrfProtection = false
maxUploadSize = 500
maxMessageSize = 500
enableCORS = false

[runner]
fastReruns = false